//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lunch.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DishStats
    {
        public int Id { get; set; }
        public int UserId { get; set; }
        public int DishId { get; set; }
        public Nullable<int> SelectionCount { get; set; }
        public Nullable<byte> Rating { get; set; }
    
        public virtual Dish Dish { get; set; }
        public virtual User User { get; set; }
    }
}
