//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lunch.WebApi.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Menu
    {
        public Menu()
        {
            this.UserMenus = new HashSet<UserMenu>();
        }
    
        public int Id { get; set; }
        public Nullable<int> DishId { get; set; }
        public Nullable<int> DishCategoryId { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Serial { get; set; }
    
        public virtual Dish Dish { get; set; }
        public virtual DishCategory DishCategory { get; set; }
        public virtual ICollection<UserMenu> UserMenus { get; set; }
    }
}
